## Platform detection
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_compile_definitions(HZPVR_PLATFORM_LINUX)
    set(SRC_PLATFORM_OS ${SRC_PLATFORM_LINUX})
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        add_compile_definitions(HZPVR_PLATFORM_MACOS)
        set(SRC_PLATFORM_OS ${SRC_PLATFORM_MACOS})
        find_library(COCOA_LIB Cocoa)
        find_library(IOKIT_LIB IOKit)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    add_compile_definitions(HZPVR_PLATFORM_WINDOWS)
    set(SRC_PLATFORM_OS ${SRC_PLATFORM_WINDOWS})
else()
    set(OS_NAME Unknown)
endif()
