# Set SOURCE dirs
set(SRC_ROOT_DIR src)
set(SRC_HZPVR_DIR ${SRC_ROOT_DIR}/HazelPVR)
set(SRC_HZPVR_CORE_DIR ${SRC_HZPVR_DIR}/Core)
set(SRC_HZPVR_IMGUI_DIR ${SRC_HZPVR_DIR}/ImGui)
set(SRC_HZPVR_RENDERER_DIR ${SRC_HZPVR_DIR}/Renderer)

set(SRC_PLATFORM_DIR ${SRC_ROOT_DIR}/Platform)
set(SRC_PLATFORM_LINUX_DIR ${SRC_PLATFORM_DIR}/Linux)
set(SRC_PLATFORM_MACOS_DIR ${SRC_PLATFORM_DIR}/macOS)
set(SRC_PLATFORM_OPENGL_DIR ${SRC_PLATFORM_DIR}/OpenGL)
set(SRC_PLATFORM_WINDOWS_DIR ${SRC_PLATFORM_DIR}/Windows)

# Set HEADER dirs
set(HDR_ROOT_DIR include)
set(HDR_HZPVR_DIR ${HDR_ROOT_DIR}/HazelPVR)
set(HDR_HZPVR_CORE_DIR ${HDR_HZPVR_DIR}/Core)
set(HDR_HZPVR_EVENTS_DIR ${HDR_HZPVR_DIR}/Events)
set(HDR_HZPVR_IMGUI_DIR ${HDR_HZPVR_DIR}/ImGui)
set(HDR_HZPVR_RENDERER_DIR ${HDR_HZPVR_DIR}/Renderer)

set(HDR_PLATFORM_DIR Platform)
set(HDR_PLATFORM_LINUX_DIR ${HDR_PLATFORM_DIR}/Linux)
set(HDR_PLATFORM_MACOS_DIR ${HDR_PLATFORM_DIR}/macOS)
set(HDR_PLATFORM_OPENGL_DIR ${HDR_PLATFORM_DIR}/OpenGL)
set(HDR_PLATFORM_WINDOWS_DIR ${HDR_PLATFORM_DIR}/Windows)

# Set headers to be precompiled
set(PCH ${HDR_ROOT_DIR}/hzpvrpch.hpp)

# VENDOR dirs
set(VENDOR_ROOT_DIR vendor)
set(GLAD ${VENDOR_ROOT_DIR}/glad)
set(GLFW ${VENDOR_ROOT_DIR}/glfw)
set(GLM ${VENDOR_ROOT_DIR}/glm)
set(IMGUI ${VENDOR_ROOT_DIR}/imgui)
set(SPDLOG ${VENDOR_ROOT_DIR}/spdlog)
set(STB_IMAGE ${VENDOR_ROOT_DIR}/stb_image)

# VENDOR include dirs
set(SPDLOG_HDR ${SPDLOG}/include)
set(GLAD_HDR ${GLAD}/include)
set(GLFW_HDR ${GLFW}/include)





############### FILE GLOBBING ###############

# Glob SOURCE files
file(GLOB SRC_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_ROOT_DIR}/*.cpp)
file(GLOB SRC_HZPVR ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_HZPVR_DIR}/*.cpp)
file(GLOB SRC_HZPVR_CORE ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_HZPVR_CORE_DIR}/*.cpp)
file(GLOB SRC_HZPVR_IMGUI ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_HZPVR_IMGUI_DIR}/*.cpp)
file(GLOB SRC_HZPVR_RENDERER ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_HZPVR_RENDERER_DIR}/*.cpp)
file(GLOB SRC_PLATFORM ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_PLATFORM_DIR}/*.cpp)
file(GLOB SRC_PLATFORM_LINUX ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_PLATFORM_LINUX_DIR}/*.cpp)
file(GLOB SRC_PLATFORM_MACOS ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_PLATFORM_MACOS_DIR}/*.cpp)
file(GLOB SRC_PLATFORM_OPENGL ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_PLATFORM_OPENGL_DIR}/*.cpp)
file(GLOB SRC_PLATFORM_WINDOWS ${CMAKE_CURRENT_SOURCE_DIR}/${SRC_PLATFORM_WINDOWS_DIR}/*.cpp)

set(SRC_STB_IMAGE ${STB_IMAGE}/stb_image.cpp)

# Glob HEADER files
file(GLOB HDR_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_ROOT_DIR}/*.hpp)
file(GLOB HDR_HZPVR ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_HZPVR_DIR}/*.hpp)
file(GLOB HDR_HZPVR_CORE ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_HZPVR_CORE_DIR}/*.hpp)
file(GLOB HDR_HZPVR_EVENTS ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_HZPVR_EVENTS_DIR}/*.hpp)
file(GLOB HDR_HZPVR_IMGUI ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_HZPVR_IMGUI_DIR}/*.hpp)
file(GLOB HDR_HZPVR_RENDERER ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_HZPVR_RENDERER_DIR}/*.hpp)
file(GLOB HDR_PLATFORM ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_PLATFORM_DIR}/*.hpp)
file(GLOB HDR_PLATFORM_LINUX ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_PLATFORM_LINUX_DIR}/*.hpp)
file(GLOB HDR_PLATFORM_MACOS ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_PLATFORM_MACOS_DIR}/*.hpp)
file(GLOB HDR_PLATFORM_OPENGL ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_PLATFORM_OPENGL_DIR}/*.hpp)
file(GLOB HDR_PLATFORM_WINDOWS ${CMAKE_CURRENT_SOURCE_DIR}/${HDR_PLATFORM_WINDOWS_DIR}/*.hpp)