## Set platform attributes
if(OS STREQUAL Linux)
    set(SRC_PLATFORM_OS ${SRC_PLATFORM_LINUX})
elseif(OS STREQUAL Darwin)
    set(SRC_PLATFORM_OS ${SRC_PLATFORM_MACOS})
    find_library(COCOA_LIB Cocoa)
    find_library(IOKIT_LIB IOKit)
elseif(OS STREQUAL Windows)
    set(SRC_PLATFORM_OS ${SRC_PLATFORM_WINDOWS})
endif()
